"""Version 1

Revision ID: 088ebda35568
Revises: 5d2edc158d16
Create Date: 2026-02-21 11:27:54.994762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088ebda35568'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metodos_pago',
        sa.Column('id', sa.Integer, nullable=False),
        sa.Column('nombre', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('platillos',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nombre', sa.String(), nullable=True),
        sa.Column('precio', sa.DECIMAL(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(),
            server_default=sa.text('now()'), nullable=True),
        sa.Column('update_at', sa.TIMESTAMP(),
            server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('proveedores',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nombre', sa.String(), nullable=True),
        sa.Column('contacto', sa.String(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(),
            server_default=sa.text('now()'), nullable=True),
        sa.Column('update_at', sa.TIMESTAMP(),
            server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('tipo_platillos',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('categoria', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('inventario',
        sa.Column('id', sa.UUID(), nullable=False, primary_key=True),
        sa.Column('nombre_insumo', sa.String(), nullable=False),
        sa.Column('categoria', sa.String(), nullable=False),
        sa.Column('cantidad', sa.Integer, nullable=True),
        sa.Column('precio_compra', sa.DECIMAL(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(),
            server_default=sa.text('now()'), nullable=True),
        sa.Column('update_at', sa.TIMESTAMP(),
            server_default=sa.text('now()'), nullable=True),
    )

    op.create_table('registro_de_pagos',
        sa.Column('id', sa.UUID(), nullable=False),
        #sa.Column('id_platillo', sa.UUID(), nullable=False),
        sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
        #sa.Column('cantidad', sa.Integer(), nullable=False),
        sa.Column('total_venta', sa.DECIMAL(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(),
            server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['id_metodo_pago'], ['metodos_pago.id'], ),
        #sa.ForeignKeyConstraint(['id_platillo'], ['platillos.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('receta_platillos',
        sa.Column('id_platillo', sa.UUID(), nullable=False),
        sa.Column('id_insumo', sa.UUID(), nullable=False),
        sa.Column('cantidad_usada', sa.DECIMAL(), nullable=True),
        sa.ForeignKeyConstraint(['id_insumo'], ['inventario.id'], ),
        sa.ForeignKeyConstraint(['id_platillo'], ['platillos.id'], ),
        sa.PrimaryKeyConstraint('id_platillo', 'id_insumo'),
        sa.UniqueConstraint('id_insumo', 'id_platillo')
    )
    
    op.create_table('detalle_pagos',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('id_pago', sa.UUID(), nullable=False),
        sa.Column('id_platillo', sa.UUID(), nullable=False),
        sa.Column('cantidad', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['id_pago'], ['registro_de_pagos.id'], ),
        sa.ForeignKeyConstraint(['id_platillo'], ['platillos.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receta_platillo')
    op.drop_table('registro_de_pagos')
    op.drop_table('inventario')
    op.drop_table('tipo_platillo')
    op.drop_table('proveedor')
    op.drop_table('platillos')
    op.drop_table('metodo_pago')
    op.drop_table('detalle_pagos')
    # ### end Alembic commands ###
