"""empty message

Revision ID: bc3472f243eb
Revises: 6a33399f9b1b
Create Date: 2026-02-28 19:12:26.811105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc3472f243eb'
down_revision: Union[str, Sequence[str], None] = '8efda3b3367e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """ op.drop_column('inventario', 'precio_compra')
    op.drop_column('inventario', 'categoria')
    op.drop_column('inventario', 'nombre_insumo')
    op.drop_column('inventario', 'created_at')
    op.drop_column('inventario', 'cantidad')
    op.drop_column('inventario', 'update_at') """
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """ op.add_column('inventario', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('inventario', sa.Column('cantidad', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('inventario', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('inventario', sa.Column('nombre_insumo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('inventario', sa.Column('categoria', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('inventario', sa.Column('precio_compra', sa.NUMERIC(), autoincrement=False, nullable=True)) """
    # ### end Alembic commands ###
